config/routes.rb
Rails.application.routes.draw do
  resources :owners
  get 'owner/new'

  get 'owner/index'

  get 'owner/create'

  get 'owner/view'

  get 'owner/update'

  get 'owner/destroy'

  resources :rest_lists
  root 'rest_lists#index'

end

app/models/owner.rb
class Owner < ActiveRecord::Base
	has_many :rest_lists, through: :rest_owners 
	has_many :rest_owners
end

app/models/rest_list.rb
class RestList < ActiveRecord::Base
  has_many :owners, through: :rest_owners 
  has_many :rest_owners
  validates :rest_name, :presence => {:message => "Restaurant Name is a Required Field"}
  validates :phone_num, :presence => {:message => "Phone Number is a Required Field"}
  validates_format_of :phone_num, :with => /\A(\+1|1)?([2-9]\d\d[2-9]\d{6})\z/, message: 'This number isn\'t formatted properly, try it like 555-555-5555'
  validates :street_address, :presence => {:message => "Street Address is a Required Field"}
  validates :city, :presence => {:message => "City is a Required Field"}
  validates :state, :presence => {:message => "State is a Required Field"}
  validates :zipcode, :presence => {:message => "Zip Code is a Required Field"}
  STATES = ['AL', 'AK', 'AS', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FM', 'FL', 'GA', 'GU', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MH', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'MP', 'OH', 'OK', 'OR', 'PW', 'PA', 'PR', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VI', 'VA', 'WA', 'WV', 'WI', 'WY', 'AE', 'AA', 'AP']
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rest_lists_controller.rb
class RestListsController < ApplicationController
  before_action :set_rest_list, only: [:show, :edit, :update, :destroy, :map_link, :yelp_review]

  # GET /rest_lists
  # GET /rest_lists.json
  def index
    @rest_lists = RestList.all
  end

  # GET /rest_lists/1
  # GET /rest_lists/1.json
  def show
  	map_link
  end

  # GET /rest_lists/new
  def new
    @rest_list = RestList.new
  end

  # GET /rest_lists/1/edit
  def edit
  end

  # POST /rest_lists
  # POST /rest_lists.json
  def create
    @rest_list = RestList.new(rest_list_params)
	
    respond_to do |format|
      if @rest_list.save
        format.html { redirect_to @rest_list, notice: 'Rest list was successfully created.' }
        format.json { render :show, status: :created, location: @rest_list }
      else
        format.html { render :new }
        format.json { render json: @rest_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rest_lists/1
  # PATCH/PUT /rest_lists/1.json
  def update
    respond_to do |format|
      if @rest_list.update(rest_list_params)
        format.html { redirect_to @rest_list, notice: 'Rest list was successfully updated.' }
        format.json { render :show, status: :ok, location: @rest_list }
      else
        format.html { render :edit }
        format.json { render json: @rest_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rest_lists/1
  # DELETE /rest_lists/1.json
  def destroy
    @rest_list.destroy
    respond_to do |format|
      format.html { redirect_to rest_lists_url, notice: 'Rest list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def map_link
  	map_url_array = ["https://maps.googleapis.com/maps/api/staticmap?markers="]
  	map_url_array.push(@rest_list.street_address.split(" ").join("+"))
  	map_url_array.push("+")
  	map_url_array.push(@rest_list.city.split(" ").join("+"))
  	map_url_array.push("+")
  	map_url_array.push(@rest_list.state)
  	map_url_array.push("+")
  	map_url_array.push(@rest_list.zipcode)
  	map_url_array.push("+")
  	map_url_array.push(@rest_list.city.split(" ").join("+"))
  	map_url_array.push("&zoom=16&size=400x400&key=")
  	map_url_array.push("#{Rails.application.secrets.google_map_api}")
  	@map_url_string = map_url_array.join
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rest_list
      @rest_list = RestList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rest_list_params
      params.require(:rest_list).permit(:rest_name, :description, :phone_num, :street_address, :city, :state, :zipcode, :menu_link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rest_lists_helper.rb
module RestListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RestaurantList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/rest_lists/_form.html.erb
<%= form_for(@rest_list) do |f| %>
  <% if @rest_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rest_list.errors.count, "error") %> prohibited this rest_list from being saved:</h2>

      <ul>
      <% @rest_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rest_name %><br>
    <%= f.text_field :rest_name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :phone_num %><br>
    <%= f.text_field :phone_num %>
  </div>
  <div class="field">
    <%= f.label :street_address %><br>
    <%= f.text_field :street_address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.collection_select :state, RestList::STATES, :to_s, :to_s, 
       :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :zipcode %><br>
    <%= f.text_field :zipcode %>
  </div>
  <div class="field">
    <%= f.label :menu_link %><br>
    <%= f.text_field :menu_link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rest_lists/edit.html.erb
<h1>Editing Rest List</h1>

<%= render 'form' %>

<%= link_to 'Show', @rest_list %> |
<%= link_to 'Back', rest_lists_path %>

app/views/rest_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Restaurant List</h1>

<table>
  <thead>
    <tr>
      <th>Rest name</th>
      <th>Description</th>
      <th>Phone num</th>
      <th>Street address</th>
      <th>City</th>
      <th>State</th>
      <th>Zipcode</th>
      <th>Menu link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rest_lists.each do |rest_list| %>
      <tr>
        <td><%= rest_list.rest_name %></td>
        <td><%= rest_list.description %></td>
        <td><%= rest_list.phone_num %></td>
        <td><%= rest_list.street_address %></td>
        <td><%= rest_list.city %></td>
        <td><%= rest_list.state %></td>
        <td><%= rest_list.zipcode %></td>
        <td><%= rest_list.menu_link %></td>
        <td><%= link_to 'Show', rest_list %></td>
        <td><%= link_to 'Edit', edit_rest_list_path(rest_list) %></td>
        <td><%= link_to 'Destroy', rest_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rest list', new_rest_list_path %>

app/views/rest_lists/new.html.erb
<h1>Add a New Resturant</h1>

<%= render 'form' %>

<%= link_to 'Back', rest_lists_path %>
<%= link_to 'Home', root_path %>

app/views/rest_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rest name:</strong>
  <%= @rest_list.rest_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @rest_list.description %>
</p>

<p>
  <strong>Phone num:</strong>
  <%= @rest_list.phone_num %>
</p>

<p>
  <strong>Street address:</strong>
  <br>
  <%= @rest_list.street_address %>
  <br>
  <%= @rest_list.city %>, <%= @rest_list.state %>
  <%= @rest_list.zipcode %>
</p>

<p>
  <strong>Menu link:</strong>
  <%= @rest_list.menu_link %>
</p>
<p>
<strong>Map</strong>
</p>
<%= image_tag("#{@map_url_string}", :alt => "Restaurant Map") %>
<br>


<%= link_to 'Edit', edit_rest_list_path(@rest_list) %> |
<%= link_to 'Back', rest_lists_path %>